#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);
MODULE_INFO(name, KBUILD_MODNAME);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

#ifdef CONFIG_RETPOLINE
MODULE_INFO(retpoline, "Y");
#endif

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xa595df7e, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xcfb1cc40, __VMLINUX_SYMBOL_STR(register_netdevice) },
	{ 0x4e251c31, __VMLINUX_SYMBOL_STR(kobject_put) },
	{ 0x53afe696, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0xe7df9227, __VMLINUX_SYMBOL_STR(neigh_lookup) },
	{ 0x9bb7af9a, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x29c20a79, __VMLINUX_SYMBOL_STR(stp_proto_unregister) },
	{ 0xf7aa17bf, __VMLINUX_SYMBOL_STR(sysfs_remove_bin_file) },
	{ 0x5fc56a46, __VMLINUX_SYMBOL_STR(_raw_spin_unlock) },
	{ 0xcfefe1e, __VMLINUX_SYMBOL_STR(percpu_counter_destroy) },
	{ 0x7b52e38, __VMLINUX_SYMBOL_STR(rtnl_unregister) },
	{ 0x91eb9b4, __VMLINUX_SYMBOL_STR(round_jiffies) },
	{ 0xcedc227c, __VMLINUX_SYMBOL_STR(netdev_notice) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0x5c2e3421, __VMLINUX_SYMBOL_STR(del_timer) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xeef5609f, __VMLINUX_SYMBOL_STR(dev_get_flags) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0x4118c56d, __VMLINUX_SYMBOL_STR(dev_disable_lro) },
	{ 0xfe90c4a6, __VMLINUX_SYMBOL_STR(_find_first_zero_bit_le) },
	{ 0x79aa04a2, __VMLINUX_SYMBOL_STR(get_random_bytes) },
	{ 0xd5104f, __VMLINUX_SYMBOL_STR(dev_uc_add) },
	{ 0xfe3cad58, __VMLINUX_SYMBOL_STR(netdev_rx_handler_register) },
	{ 0xc7a4fbed, __VMLINUX_SYMBOL_STR(rtnl_lock) },
	{ 0x95021a34, __VMLINUX_SYMBOL_STR(arp_tbl) },
	{ 0x507c7f57, __VMLINUX_SYMBOL_STR(kobject_uevent) },
	{ 0x9f4cc256, __VMLINUX_SYMBOL_STR(netif_carrier_on) },
	{ 0xaaa21787, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0xa1d55e90, __VMLINUX_SYMBOL_STR(_raw_spin_lock_bh) },
	{ 0xdc9b716f, __VMLINUX_SYMBOL_STR(skb_clone) },
	{ 0x20000329, __VMLINUX_SYMBOL_STR(simple_strtoul) },
	{ 0x78443918, __VMLINUX_SYMBOL_STR(skb_copy) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x2124474, __VMLINUX_SYMBOL_STR(ip_send_check) },
	{ 0xd2da1048, __VMLINUX_SYMBOL_STR(register_netdevice_notifier) },
	{ 0xbb7729f1, __VMLINUX_SYMBOL_STR(netif_carrier_off) },
	{ 0x9e7af1a1, __VMLINUX_SYMBOL_STR(rtnl_notify) },
	{ 0xfcf3c907, __VMLINUX_SYMBOL_STR(netdev_master_upper_dev_get) },
	{ 0x38e2565b, __VMLINUX_SYMBOL_STR(dev_set_allmulti) },
	{ 0xa37af67d, __VMLINUX_SYMBOL_STR(is_skb_forwardable) },
	{ 0x5250f724, __VMLINUX_SYMBOL_STR(call_netdevice_notifiers) },
	{ 0x5ee52022, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x28cc25db, __VMLINUX_SYMBOL_STR(arm_copy_from_user) },
	{ 0xfd792e2a, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0xd530f9d8, __VMLINUX_SYMBOL_STR(kobject_del) },
	{ 0xa66de058, __VMLINUX_SYMBOL_STR(neigh_destroy) },
	{ 0xf499fdb2, __VMLINUX_SYMBOL_STR(rcu_barrier_bh) },
	{ 0x28aa6a67, __VMLINUX_SYMBOL_STR(call_rcu) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0x456913ac, __VMLINUX_SYMBOL_STR(sysfs_remove_group) },
	{ 0x526c3a6c, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xc9ec4e21, __VMLINUX_SYMBOL_STR(free_percpu) },
	{ 0x9d0d6206, __VMLINUX_SYMBOL_STR(unregister_netdevice_notifier) },
	{ 0xf4fa543b, __VMLINUX_SYMBOL_STR(arm_copy_to_user) },
	{ 0x66f05892, __VMLINUX_SYMBOL_STR(nf_hook_slow) },
	{ 0x2046519f, __VMLINUX_SYMBOL_STR(skb_trim) },
	{ 0x2c50f62d, __VMLINUX_SYMBOL_STR(kobject_create_and_add) },
	{ 0x131db64a, __VMLINUX_SYMBOL_STR(system_long_wq) },
	{ 0x4e810d22, __VMLINUX_SYMBOL_STR(cpumask_next) },
	{ 0xb04cd7b4, __VMLINUX_SYMBOL_STR(netdev_master_upper_dev_link) },
	{ 0xf9df5631, __VMLINUX_SYMBOL_STR(__netdev_alloc_skb) },
	{ 0x8dee9885, __VMLINUX_SYMBOL_STR(ip_mc_check_igmp) },
	{ 0x19e2d194, __VMLINUX_SYMBOL_STR(netif_rx) },
	{ 0x497e285, __VMLINUX_SYMBOL_STR(__pskb_pull_tail) },
	{ 0x17de3d5, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0xf1db1704, __VMLINUX_SYMBOL_STR(nla_memcpy) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0xfc982daa, __VMLINUX_SYMBOL_STR(del_timer_sync) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xb45f2d4, __VMLINUX_SYMBOL_STR(__cpu_possible_mask) },
	{ 0xbef171bf, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x9fdecc31, __VMLINUX_SYMBOL_STR(unregister_netdevice_many) },
	{ 0x8dff2b72, __VMLINUX_SYMBOL_STR(sysfs_rename_link_ns) },
	{ 0xfc934a29, __VMLINUX_SYMBOL_STR(stp_proto_register) },
	{ 0x4ecfe54b, __VMLINUX_SYMBOL_STR(__ethtool_get_link_ksettings) },
	{ 0x6d294e43, __VMLINUX_SYMBOL_STR(clock_t_to_jiffies) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xbbaea711, __VMLINUX_SYMBOL_STR(ethtool_op_get_link) },
	{ 0x20c55ae0, __VMLINUX_SYMBOL_STR(sscanf) },
	{ 0x3c3fce39, __VMLINUX_SYMBOL_STR(__local_bh_enable_ip) },
	{ 0xdcab5c07, __VMLINUX_SYMBOL_STR(sysfs_create_group) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x6844a3d4, __VMLINUX_SYMBOL_STR(inet_select_addr) },
	{ 0x32b890e3, __VMLINUX_SYMBOL_STR(ns_capable) },
	{ 0xc917e655, __VMLINUX_SYMBOL_STR(debug_smp_processor_id) },
	{ 0x51f4f043, __VMLINUX_SYMBOL_STR(__skb_warn_lro_forwarding) },
	{ 0xa4922285, __VMLINUX_SYMBOL_STR(kobject_init_and_add) },
	{ 0x8b211f01, __VMLINUX_SYMBOL_STR(mod_delayed_work_on) },
	{ 0xcd279169, __VMLINUX_SYMBOL_STR(nla_find) },
	{ 0x9372bc7d, __VMLINUX_SYMBOL_STR(free_netdev) },
	{ 0x2524ebb5, __VMLINUX_SYMBOL_STR(llc_mac_hdr_init) },
	{ 0x6938a2bc, __VMLINUX_SYMBOL_STR(register_netdev) },
	{ 0x9cd838e4, __VMLINUX_SYMBOL_STR(nla_put) },
	{ 0x84dbef6f, __VMLINUX_SYMBOL_STR(netif_receive_skb) },
	{ 0x4578926f, __VMLINUX_SYMBOL_STR(netdev_upper_dev_unlink) },
	{ 0x84b183ae, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0x6df49869, __VMLINUX_SYMBOL_STR(ndo_dflt_fdb_dump) },
	{ 0x73e20c1c, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0xe5196a4f, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x1b1bcf02, __VMLINUX_SYMBOL_STR(skb_push) },
	{ 0x85a6237f, __VMLINUX_SYMBOL_STR(rtnl_register) },
	{ 0x9555f16c, __VMLINUX_SYMBOL_STR(arp_send) },
	{ 0xf4f14de6, __VMLINUX_SYMBOL_STR(rtnl_trylock) },
	{ 0xa7eedcc4, __VMLINUX_SYMBOL_STR(call_usermodehelper) },
	{ 0xa38caae0, __VMLINUX_SYMBOL_STR(mod_timer) },
	{ 0x68c2b9e8, __VMLINUX_SYMBOL_STR(rtnl_af_unregister) },
	{ 0x2469810f, __VMLINUX_SYMBOL_STR(__rcu_read_unlock) },
	{ 0x815bb3c3, __VMLINUX_SYMBOL_STR(sysfs_remove_link) },
	{ 0xb3a078ee, __VMLINUX_SYMBOL_STR(skb_pull) },
	{ 0x72d9aa06, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0xa374077d, __VMLINUX_SYMBOL_STR(try_to_del_timer_sync) },
	{ 0x2ce6e793, __VMLINUX_SYMBOL_STR(rtnl_link_unregister) },
	{ 0xe9850039, __VMLINUX_SYMBOL_STR(__dev_get_by_index) },
	{ 0x600bf469, __VMLINUX_SYMBOL_STR(nla_reserve_64bit) },
	{ 0x6c209eab, __VMLINUX_SYMBOL_STR(__alloc_percpu_gfp) },
	{ 0xc1e67b3a, __VMLINUX_SYMBOL_STR(sysfs_create_link) },
	{ 0xafa0946f, __VMLINUX_SYMBOL_STR(rtnl_set_sk_err) },
	{ 0xe162e43f, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xc119d4c8, __VMLINUX_SYMBOL_STR(__alloc_skb) },
	{ 0xa6632226, __VMLINUX_SYMBOL_STR(rtnl_af_register) },
	{ 0xdd3916ac, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_bh) },
	{ 0x85ded073, __VMLINUX_SYMBOL_STR(nla_parse) },
	{ 0x21766e3a, __VMLINUX_SYMBOL_STR(netdev_rx_handler_unregister) },
	{ 0xe21f5607, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0x94c38734, __VMLINUX_SYMBOL_STR(nla_put_nohdr) },
	{ 0x6b2dc060, __VMLINUX_SYMBOL_STR(dump_stack) },
	{ 0xdbec15ae, __VMLINUX_SYMBOL_STR(passthru_features_check) },
	{ 0xde48bb98, __VMLINUX_SYMBOL_STR(alloc_netdev_mqs) },
	{ 0x4d82e8f4, __VMLINUX_SYMBOL_STR(brioctl_set) },
	{ 0xa9fc32f8, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0xef2fdc4f, __VMLINUX_SYMBOL_STR(__percpu_counter_init) },
	{ 0x38c27d25, __VMLINUX_SYMBOL_STR(netdev_err) },
	{ 0xac603833, __VMLINUX_SYMBOL_STR(ether_setup) },
	{ 0x9ca89761, __VMLINUX_SYMBOL_STR(__dev_get_by_name) },
	{ 0x935403ba, __VMLINUX_SYMBOL_STR(netdev_state_change) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x341dbfa3, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0xd4e67e66, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x7e927f92, __VMLINUX_SYMBOL_STR(call_rcu_bh) },
	{ 0x32393456, __VMLINUX_SYMBOL_STR(unregister_netdevice_queue) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0xaa627ec9, __VMLINUX_SYMBOL_STR(dev_set_promiscuity) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x5f5852b5, __VMLINUX_SYMBOL_STR(dev_get_iflink) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xab852712, __VMLINUX_SYMBOL_STR(sysfs_create_bin_file) },
	{ 0xb8572d07, __VMLINUX_SYMBOL_STR(rtnl_link_register) },
	{ 0xb2409f34, __VMLINUX_SYMBOL_STR(dev_uc_del) },
	{ 0x5f4cdf73, __VMLINUX_SYMBOL_STR(nla_put_64bit) },
	{ 0xefd6cf06, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr0) },
	{ 0x7d0db45c, __VMLINUX_SYMBOL_STR(jiffies_to_clock_t) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0xe113bbbc, __VMLINUX_SYMBOL_STR(csum_partial) },
	{ 0x9792c9e9, __VMLINUX_SYMBOL_STR(consume_skb) },
	{ 0xe627b3d9, __VMLINUX_SYMBOL_STR(netdev_update_features) },
	{ 0x85670f1d, __VMLINUX_SYMBOL_STR(rtnl_is_locked) },
	{ 0x314ad603, __VMLINUX_SYMBOL_STR(sysfs_create_file_ns) },
	{ 0x489e9dcf, __VMLINUX_SYMBOL_STR(dev_queue_xmit) },
	{ 0x8d522714, __VMLINUX_SYMBOL_STR(__rcu_read_lock) },
	{ 0xf229424a, __VMLINUX_SYMBOL_STR(preempt_count_add) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x3d107dd6, __VMLINUX_SYMBOL_STR(skb_put) },
	{ 0x3eeba61b, __VMLINUX_SYMBOL_STR(__nlmsg_put) },
	{ 0xc3a76bf0, __VMLINUX_SYMBOL_STR(skb_copy_bits) },
	{ 0x6e720ff2, __VMLINUX_SYMBOL_STR(rtnl_unlock) },
	{ 0xc58a8cd, __VMLINUX_SYMBOL_STR(netdev_increment_features) },
	{ 0x7dcaf5b0, __VMLINUX_SYMBOL_STR(dev_set_mtu) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=stp";


MODULE_INFO(srcversion, "7C57ACDA1F3ECD0B1C589A5");
