#obj-$(CONFIG_MXC_MLB) += mlb/
#obj-$(CONFIG_MXC_SIM) += sim/
#obj-$(CONFIG_MXC_VPU) += vpu/
#obj-$(CONFIG_MXC_IPU_V3) += ipu3/
#obj-$(CONFIG_MXC_HDMI_CEC) += hdmi-cec/
#obj-$(CONFIG_MXC_GPU_VIV) += gpu-viv/
#obj-$(CONFIG_MXC_MIPI_CSI2) += mipi/
obj-y += mlb/
obj-y += sim/
obj-y += vpu/
obj-y += ipu3/
obj-y += hdmi-cec/
obj-y += gpu-viv/
obj-y += mipi/

